name: MSYS2
on: push

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          release: true
          update: true
          install: zip git mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-python mingw-w64-ucrt-x86_64-gtk3 mingw-w64-ucrt-x86_64-pkg-config mingw-w64-ucrt-x86_64-go mingw-w64-ucrt-x86_64-ntldd-git
      - name: Build
        run: |
          python3 grabTitles.py
          go build -ldflags -H=windowsgui cmd/WiiUDownloader/*.go
      - name: Deploy WiiUDownloader
        run: |
          mkdir dist
          mkdir dist/lib
          mkdir dist/share
          mkdir dist/share/icons
          mkdir dist/share/glib-2.0
          mkdir dist/share/glib-2.0/schemas/
          for ff in $(${MSYSTEM_PREFIX}/bin/ntldd -R main.exe  | tr '\\' '/' | grep -io "$(cygpath -m ${MSYSTEM_PREFIX}).\+\.dll" | sort -u); do
            cp $(cygpath -u "$ff") dist/
          done
          cp -r /ucrt64/lib/gdk-pixbuf-2.0 ./dist/lib/gdk-pixbuf-2.0
          cp -r /ucrt64/share/icons/* ./dist/share/icons/
          cp /ucrt64/share/glib-2.0/schemas/* dist/share/glib-2.0/schemas/
          glib-compile-schemas.exe dist/share/glib-2.0/schemas/
          cp main.exe dist/WiiUDownloader.exe
          cd dist && zip -9 -r ../WiiUDownloader-Windows.zip .
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: WiiUDownloader-Windows
          path: WiiUDownloader-Windows.zip
          if-no-files-found: warn
